# Generated by Django 3.0.5 on 2021-08-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='site',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
