# Generated by Django 3.0.5 on 2021-08-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210809_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('is_cadre', 'Cadre'), ('is_collaborateur', 'Non cadre')], default='is_collaborateur', max_length=20),
        ),
    ]
