# Generated by Django 3.0.5 on 2020-12-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201216_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
