# Generated by Django 3.0.5 on 2020-12-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_variant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variant',
            new_name='Variants',
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color')], default='None', max_length=10),
        ),
    ]
