# Generated by Django 3.0.5 on 2020-12-16 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variants',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variants',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
    ]
