# Generated by Django 3.0.5 on 2020-12-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201216_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variants',
            new_name='Variant',
        ),
    ]
