# Generated by Django 3.0.5 on 2021-02-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_variant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variant',
            new_name='Size',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Variant',
            new_name='size',
        ),
    ]
