# Generated by Django 3.0.5 on 2021-02-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
