# Generated by Django 3.0.5 on 2021-07-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
