# Generated by Django 3.0.5 on 2021-07-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_productattribute_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
